#! /bin/sh -ex

# This creates a fresh database
# data/current -> data/mdfirst.db
# with some content from the META-SHARE node that ./syncmeta mirrors.

mkdir --parents data

( cd data
  rm -f mdfirst.db
  sqlite3 mdfirst.db < ../schema.sql
  ln -sf mdfirst.db current )

./syncmeta --see=53
./syncmeta --see=73
./syncmeta --see=53,73
