---
# The Language Bank of Finland Software Stack on CSC's Puhti
#

- name: "Set hpc vars"
  hosts: hpc
  vars:
   hfst_version: 3.16.0
   hfst_ospell_version: 0.5.1
   praat_version: 6.4
   finnish_tagtools_version: 1.6.0
   udpipe_version: 1.4.0
   tsv_tools_version: 2.2.0
   vrt_tools_version: 1.0

  become: false
  gather_facts: true
  gather_subset:
   - '!all' # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/setup_module.html
  roles:
   - { role: hfst, tags: hfst }
   - { role: hfst-morphologies, tags: hfst-morphologies }
   - { role: check-hfst, tags: check-hfst }
   - { role: praat, tags: praat }
   - { role: udpipe, tags: udpipe }
   - { role: enchant, tags: enchant }
   - { role: opensmile, tags: opensmile }
   - { role: trankit, tags: trankit }

- { name: "Import Heliots", import_playbook: heliots/heliots.yml, tags: heliots }
- { name: "Import vrt-tools", import_playbook: vrt-tools/vrt-tools.yml, tags: vrt-tools }
- { name: "Import tsv-utils", import_playbook: tsv-utils/tsv-utils.yml, tags: tsv-utils }
- { name: "Import tagtools", import_playbook: finnish-tagtools/finnish-tagtools.yml, tags: finnish-tagtools }
