---
# The Language Bank of Finland Software Stack on CSC's Taito-cluster
#

- hosts: hpc
  vars:
   - hfst_version: 3.16.0
   - hfst_ospell_version: 0.5.1
   - finnish_parse_version: 1.0
   - praat_version: 6.2.17
   - finnish_tagtools_version: 1.6.0
#   - kaldi_version:
#      number: 5.5.219
#      githash:  06bf62a57
   - aalto_asr_version:
       number: 2.1
       githash: latest
   - hunpos_version: 1.0
   - sparv_pipeline_version: 2.0_MIT_2017-10-23
#  - ffmpeg_version: see roles/ffmpeg/defaults/main.yml
   - udpipe_version: 1.2.0
   - bert_models:
       - TurkuNLP/bert-base-finnish-cased-v1
       - TurkuNLP/bert-base-finnish-uncased-v1
   - tsv_tools_version: 2.2.1
   - heliots_version: 1.3
   - vrt_tools_version: 1.0
      

  become: no
  gather_facts: true
  gather_subset: min
  roles:
   - { role: hfst, tags: hfst }
   - { role: hfst-morphologies, tags: hfst-morphologies }
   - { role: hfst-ospell, tags: hfst-ospell }
   - { role: check-hfst, tags: check-hfst }
   - { role: finnish-parse, branch: master, tags: finnish-parse }
   - { role: praat, tags: praat }
# disabled, managed with Spack now
#   - { role: ffmpeg, branch: master, tags: ffmpeg }
   - { role: finnish-tagtools, tags: finnish-tagtools }
#   - { role: kaldi    , tags: kaldi }
   - { role: aalto-asr, tags: aalto-asr }
   - { role: udpipe, tags: udpipe }
   - { role: hunpos, tags: hunpos }
   - { role: sparv_pipeline, tags: sparv_pipeline }
#   - { role: bert_models , tags: bert_models }
   - { role: tsv-utils , tags: tsv-utils }
- { import_playbook: heliots/heliots.yml , tags: heliots }
- { import_playbook: vrt-tools/vrt-tools.yml , tags: vrt-tools }



     
