---

- name: Ensure directories exists
  become: no
  command: mkdir -p "{{ item }}"
  args:
    creates: "{{ item }}"
    warn: false
  loop:
    - "{{ src_root }}"
    - "{{ install_dir }}/bin"
    - "{{ lib_dir }}"

- name: Copy binaries and libs
  get_url:
    url: "{{ source }}"
    dest: "{{ install_dir }}/lib/{{ jar_name }}"


- name: create wrapper scripts
  template:
    src: heliots.j2
    dest: "{{ install_dir }}/bin/{{ item }}"
    mode: 0755
  loop:
    - heliots

- name: Fix permissions (if shared group is set)
  file:
    path: "{{ install_dir }}"
    group: "{{ shared_group }}"
    mode: "g+rwX,o+rX"
    recurse: yes
  when: shared_group is defined
