---
# tasks file for hfst-morphologies

- name: "Debian/Ubuntu: Install list of packages"
  apt:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - unzip
  when:
    - ansible_os_family == "Debian"
    - is_admin

- name: "RHEL/CentOS: Install list of packages"
  yum: 
    name: " {{item}} "
    state: present
  become: yes
  with_items:
    - unzip
  when:
    - ansible_os_family == "RedHat"
    - is_admin


- name: Download and extract tarball
  unarchive:
    src={{ release_url }}/{{ item.dir }}/{{ item.pkg }}.zip
    dest={{ temp_dir }}
    creates={{ temp_dir }}/{{ item.pkg }}/hfst-{{ item.lang }}-installable/Makefile
    remote_src=yes
    validate_certs=false
  loop: "{{ morphologies }}"

- name: Running make install
  shell: "make install prefix={{ hfst_install_dir }} > MAKE_INSTALL.log"
  args:
    chdir: "{{ temp_dir }}/{{ item.pkg }}/hfst-{{ item.lang }}-installable"
  loop: "{{ morphologies }}"

- name: Fix permissions (again)
  file:
    path={{ hfst_install_dir }}
    group={{ shared_group }}
    mode="g+rwX,o+rX,o-w"
    recurse=yes
  when: shared_group is defined
