- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled

- name: Install admin tools
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  with_items:
    - nano
    - htop
    - mytop
