---

- name: Ensure necessary directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ src_root }}"
    - "{{ install_dir }}"
    - "{{ module_path }}"

- name: Get source
  ansible.builtin.unarchive:
    src: "{{ source_url }}"
    dest: "{{ src_root }}"
    remote_src: true
    creates: "{{ build_dir }}"

- name: Build
  ansible.builtin.shell:
    cmd: /bin/bash -i -c "/bin/bash build.sh {{ build_opts }}"
    chdir: "{{ build_dir }}"
    creates: "{{ build_dir }}/build/progsrc/smilextract/SMILExtract"

- name: Copy executable to final location
  ansible.builtin.copy:
    src: "{{ build_dir }}/build/progsrc/smilextract/SMILExtract"
    dest: "{{ install_dir }}"
    mode: 0775
    remote_src: true

- name: Copy scripts and config to final location
  ansible.builtin.copy:
    src: "{{ build_dir }}/{{ item }}"
    dest: "{{ install_dir }}"
    remote_src: true
  loop:
    - scripts
    - config

- name: Remove build directory
  ansible.builtin.file:
    path: "{{ build_dir }}"
    state: absent

- name: Create lmod module
  ansible.builtin.template:
    src: module_template.j2
    dest: "{{ module_path }}/{{version}}.lua"
    mode: 0664

- name: Fix permissions (if shared group is set)
  file:
    path: "{{ item }}"
    group: "{{ shared_group }}"
    mode: "g+rwX,o+rX,o-w"
    recurse: yes
  with_items:
    - "{{ install_dir }}"
    - "{{ model_package_install_dir }}"
  when: shared_group is defined
