<metadata
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xsl:version="1.0"
    xmlns:info="http://www.ilsp.gr/META-XMLSchema">
  <olac:olac
      xmlns:dc="http://purl.org/dc/elements/1.1/"
      xmlns:dcterms="http://purl.org/dc/terms/"
      xmlns:olac="http://www.language-archives.org/OLAC/1.1/"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.language-archives.org/OLAC/1.1/
			  http://www.language-archives.org/OLAC/1.1/olac.xsd">
    <TODO/>
    <dc:title>
      <xsl:value-of
	  select="descendant::info:resourceName"/>
    </dc:title>
    <dc:description>
      <xsl:value-of
	  select="descendant::info:description"/>
    </dc:description>
  </olac:olac>
</metadata>
