---
# tasks file for tsv-tools

- name: Setup directories
  become: no
  file:
    path: "{{ item }}"
    mode: "g+rwX,o+rX,o-w"
    recurse: yes
    state: directory
  loop:
    -  "{{ src_root }}"
    -  "{{ module_path }}"
    -  "{{ install_dir }}/bin/"

- name: Get source
  unarchive:
    src: "{{ release_url }}"
    dest: "{{ src_root }}"
    remote_src: yes
    mode: "g+rwX,o+rX,o-w"

- name: Copy binaries to install_dir
  copy:
    remote_src: true
    src: "{{ compile_dir }}/bin/{{ item }}"
    dest: "{{ install_dir }}/bin/{{ item }}"
    mode: 0775
  loop:
    - csv2tsv
    - number-lines
    - tsv-filter
    - tsv-pretty
    - tsv-select
    - tsv-summarize
    - keep-header
    - tsv-append
    - tsv-join
    - tsv-sample
    - tsv-split
    - tsv-uniq

- name: Install modulefile
  template:
    src: module_template.j2
    dest: "{{ module_path }}/{{ version }}.lua"
    mode: 0664


- name: Fix permissions (if shared group is set)
  file:
    path: "{{ install_dir }}"
    group: "{{ shared_group }}"
    mode: "g+rwX,o+rX,o-w"
    recurse: yes
  when: shared_group is defined

# check that one tool is available and works as expected
- name: Quick test
  shell:
    cmd: |
      bash -i -c "module load tsv-utils && \
      echo 'x' | number-lines | grep 1 "
  when: shared_group is defined
  tags: test
