#!/bin/bash

set -euo pipefail

DIR="$1"
URL="$2"
VER="$3"

(
	export GIT_TERMINAL_PROMPT=0
	cd "$DIR" || exit
	echo "Updating $DIR"
	git fetch origin "$VER" --recurse-submodules=no
	git switch -C deploy FETCH_HEAD
	if [ "$DIR" != 'workdir' ]
	then
		git submodule update --init
	fi
)
