#!/bin/bash

set -e

DIR="$1"
URL="$2"
VER="$3"

(
	cd "$DIR" || exit
	echo "Updating $DIR"
	git fetch origin "$VER" && git reset -q --hard FETCH_HEAD
	if [ "$DIR" != 'workdir' ]
	then
		git submodule update --init
	fi
)
