---
# tasks file for praat
- name: "Debian/Ubuntu: Install list of packages"
  apt:
    name:
      - libjack-dev
    state: present
  become: yes
  when:
    - ansible_os_family == "Debian"
    - is_admin

- name: "RHEL/CentOS: Install list of packages"
  yum: 
    name:
      - libjack-devel
    state: present
  become: yes
  when:
    - ansible_os_family == "RedHat"
    - is_admin

- name: src_root directory exists with 0777 permission
  become: no
  file:
    path: "{{ src_root }}"
    mode: 0777
    recurse: yes
    state: directory

- name: Get source
  unarchive:
    src: "{{ release_url }}"
    dest: "{{ src_root }}"
    remote_src: yes

- name: Prepare barren compilation
  copy:
    remote_src: true
    src:  "{{ compile_dir }}/makefiles/makefile.defs.linux.barren"
    dest: "{{ compile_dir }}/makefile.defs"

- name: Remove static linking (experimental)
  lineinfile:
    path: "{{ compile_dir }}/makefile.defs"
    regexp: "^LIBS = -lm -lpthread( -static -static-libgcc -static-libstdc\\+\\+)?$"
    line: "LIBS = -lm -lpthread"

- name: Running make 
  shell: bash --login -c "{{ gcc_modcall }} make -j8 > MAKE.log"
  args:
    chdir: "{{ compile_dir }}"
    #creates: MAKE.log

- name: ensure directories
  become: no
  file:
    path: "{{ item.name }}"
    mode:  "{{ item.mode }}"
    recurse: no
    state: directory
  loop:
    - { name: "{{ install_dir }}/bin", mode: "0775" }
    - { name: "{{ module_path }}"    , mode: "2775" }

- name: Copy praat to install_dir
  copy:
    remote_src: true
    src: "{{ compile_dir }}/praat_barren"
    dest: "{{ install_dir }}/bin/praat"
    mode: 0775

- name: Install modulefile
  template:
    src: module_template.j2
    dest: "{{ module_path }}/{{ version }}.lua"
    mode: 0644

- name: Fix permissions (if shared group is set)
  file:
    path: "{{ item }}"
    group: "{{ shared_group }}"
    mode: "g+rwX,o+rX,o-w"
    recurse: yes
  when: shared_group is defined
  loop:
    -  "{{ install_dir }}"
    -  "{{ module_path }}"
