---
# tasks file for Pytorch

- name: Create directories
  file:
    path: "{{ install_dir }}/{{ item }}"
    state: directory
    mode: 0775
  loop: "{{ bert_models }}"
  

- name: Download model files
  get_url:
    url:  "{{ release_url }}/{{ item.0 }}/{{ item.1 }}"
    dest: "{{ install_dir }}/{{ item.0 }}"
  with_nested:
    - "{{ bert_models }}"
    - "{{ bert_files }}"
  async: 600
  poll: 0
  register: download

- name: Check Download
  async_status:
    jid: "{{ item.ansible_job_id }}"
  register: jobs_result
  loop: "{{ download.results }}"
  until: jobs_result.finished
  delay: 2
  retries: 40

- name: Copy documentation
  template:
    src: "{{ item }}.j2"
    dest: "{{ install_dir }}/{{ item }}"
  loop:
    - finbert_example.py
    - README.txt

- name: Fix permissions (again)
  file:
    path: "{{ install_dir }}"
    group: "{{ shared_group }}"
    mode: "g+rwX,o+rX,o-w"
    recurse: yes
  when: shared_group is defined


