webdomain_sanat: sanat.csc.fi
webaliases_sanat: []
webdomain_nimiarkisto: nimiarkisto.fi
webaliases_nimiarkisto: []
webdomain_termipankki: tieteentermipankki.fi
webaliases_termipankki: []

nimiarkisto_service_url: http://127.0.0.1

mediawikis: []

# https://ssl-config.mozilla.org/#server=apache&version=2.4.6&config=intermediate&openssl=1.0.2k&guideline=5.6
apache_ssl_protocol: "all -SSLv3 -TLSv1 -TLSv1.1"
apache_ssl_cipher_suite: "\
  ECDHE-ECDSA-AES128-GCM-SHA256:\
  ECDHE-RSA-AES128-GCM-SHA256:\
  ECDHE-ECDSA-AES256-GCM-SHA384:\
  ECDHE-RSA-AES256-GCM-SHA384:\
  ECDHE-ECDSA-CHACHA20-POLY1305:\
  ECDHE-RSA-CHACHA20-POLY1305:\
  DHE-RSA-AES128-GCM-SHA256:\
  DHE-RSA-AES256-GCM-SHA384"

certificate_path: /etc/pki/tls

ssl_params_sanat:
  certificate_file: "{{ certificate_path }}/certs/{{ webdomain_sanat }}.crt"
  certificate_key_file: "{{ certificate_path }}/private/{{ webdomain_sanat }}.key"
ssl_params_nimiarkisto:
  certificate_file: "{{ certificate_path }}/certs/{{ webdomain_nimiarkisto }}.crt"
  certificate_key_file: "{{ certificate_path }}/private/{{ webdomain_nimiarkisto }}.key"
ssl_params_termipankki:
  certificate_file: "{{ certificate_path }}/certs/{{ webdomain_termipankki }}.crt"
  certificate_key_file: "{{ certificate_path }}/private/{{ webdomain_termipankki }}.key"


hfst_tmp: /tmp/hfst
hfst_url: http://apertium.projectjj.com/apt/release/pool/main/h/hfst/
hfst_bin: hfst_3.14.0-1~trusty1_amd64
hfst_lib: libhfst51_3.14.0-1~trusty1_amd64
hfst_components:
 - [ '{{ hfst_bin }}' , 'sha256:70b6bdc1f2f9489a73ef1f096feac6f3f70546e5f99288fd8afaba7207e2ea9e' ]
 - [ '{{ hfst_lib }}' , 'sha256:ad9cec6b8472d8d7568aac25cc09a4af8acbf341a06e755cf918839cf1d8b56e' ]


memcached_memory_limit: 4000

# composer-merge-plugin does not support 2.x
composer_keep_updated: false
composer_version: "1.10.17"

nodejs_version: "7.10.0"

sms_xml:
  wiki_username: "SyncBot"
  wiki_password: "SyncBot12"
  debug: "True"

nimiarkisto_mapproxy_key: ''
