webdomain_sanat: sanat.csc.fi
webaliases_sanat: []
webdomain_termipankki: tieteentermipankki.fi
webaliases_termipankki: []

mediawikis: []

apache_create_vhosts: false

acme_root: /etc/letsencrypt
acme_endpoint: "https://acme.sectigo.com/v2/OV"
acme_email: ling-admin@listat.csc.fi
acme_keyid: "{{ lookup('passwordstore', 'lb_passwords/portal/acme_keyid') }}"
acme_hmac: "{{ lookup('passwordstore', 'lb_passwords/portal/acme_hmac') }}"

memcached_memory_limit: 4000

composer_keep_updated: true

elasticsearch_version: '7.x'
elasticsearch_network_host: localhost
elasticsearch_heap_size_min: 2g
elasticsearch_heap_size_max: 2g
elasticsearch_extra_options: |
  cluster.routing.allocation.disk.threshold_enabled: true
  cluster.routing.allocation.disk.watermark.flood_stage: 200mb
  cluster.routing.allocation.disk.watermark.low: 500mb
  cluster.routing.allocation.disk.watermark.high: 300mb

matomo_user: apache
matomo_group: apache
matomo_url: https://{{ webdomain_termipankki }}/matomo
matomo_symlink: /www/{{ webdomain_termipankki }}/docroot/matomo

php_version: '8.2'
php_packages_extra:
  - php-process
  - php-intl
  - php-mysqlnd
  - php-pecl-mcrypt
  - php-pecl-memcached
  - php-pecl-zip
php_date_timezone: 'Europe/Helsinki'
