---

- name: Create virtual machine on cPouta
  hosts: localhost
  remote_user: almalinux
  become: false

  roles:
    - role: kielipankki.common.create_instances
      tags: create_instances

- name: Install CSC basics
  hosts: web
  become: true
  roles:
    - role: kielipankki.common.postfix
      tags: postfix
    - role: kielipankki.common.opsview
      tags: opsview
