- src: geerlingguy.apache
  version: 2.1.2
- src: geerlingguy.memcached
  version: 1.0.8
- src: geerlingguy.composer
  version: 1.8.0
- src: geerlingguy.repo-epel
  version: 1.2.3
- src: geerlingguy.repo-remi
  version: 2.0.1
