- src: geerlingguy.apache
  version: 3.3.0
- src: geerlingguy.memcached
  version: 2.2.0
- src: geerlingguy.composer
  version: 1.9.2
- src: geerlingguy.repo-epel
  version: 3.1.1
- src: geerlingguy.repo-remi
  version: 2.0.1
- src: geerlingguy.java
  version: 2.3.1
- src: geerlingguy.elasticsearch
  version: 5.1.1
- src: 0x0i.systemd
  version: v0.3.5
