- hosts: db
  become: yes
  roles:
    - role: wikidb
      tags: db

- hosts: web
  become: yes
  vars_files:
    - vars.yml
  roles:
    - role: geerlingguy.repo-epel
    - role: geerlingguy.repo-remi
      tags: php
    - role: hfst
      tags: hfst
    - role: php
      tags: php
    - role: geerlingguy.composer
      tags: php
    - role: geerlingguy.memcached
      tags: memcached
    - role: apache_ssl
      tags: apache
    - role: geerlingguy.apache
      tags: apache
    - role: mediawiki
      tags: mediawiki
    - role: selinux
    - role: firewall
      tags: firewall
    - role: geerlingguy.java
      tags: java
    - role: geerlingguy.elasticsearch
      tags: elasticsearch

- hosts: all
  become: yes
  tasks:
    - name: Install admin tools
      yum: name={{ item }} state=present
      with_items:
        - nano
        - htop
        - mytop
