- hosts: db
  become: yes
  roles:
    - role: wikidb
      tags: db

- hosts: web
  become: yes
  roles:
    - role: base
      tags: base
    - role: geerlingguy.repo-remi
      tags: php
    - role: geerlingguy.php-versions
      tags: php
    - role: geerlingguy.php
      tags: php
    - role: geerlingguy.composer
      tags: php
    - role: geerlingguy.memcached
      tags: memcached
    - role: apache_ssl
      tags: certs
    - role: geerlingguy.apache
      tags: apache
    - role: mediawiki
      tags: mediawiki
    - role: firewall
      tags: firewall
    - role: geerlingguy.java
      tags: java
    - role: geerlingguy.elasticsearch
      tags: elasticsearch
    - role: matomo
      tags: matomo
