---
# defaults

package_name: sparv_pipeline
version: "{{ sparv_pipeline_version }}"
file_basename: "{{ package_name }}_{{ sparv_pipeline_version }}"
release_url: "https://spraakbanken.gu.se/pub/sparv.dist/sparv_pipeline/{{ file_basename }}.zip"

src_root: "{{ compile_root }}"
compile_dir: "{{ src_root }}/{{ file_basename }}"
install_dir: "{{ install_prefix }}/ling/{{ package_name }}/{{ version }}"

kuhumcst_url: "https://github.com/kuhumcst/"
kuhumcst_git_pkgs: 
 - { name: "cstlemma",   githash: "9b02944" } # v8.1.2
 - { name: "hashmap",    githash: "0fcb7a9" } # 11/2016
 - { name: "letterfunc", githash: "842f97f" } # 04/2022
 - { name: "parsesgml",  githash: "978bbb6" } # 08/2014
